version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # Web UI порт
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      MINIO_ENDPOINT: http://minio:9000
      MINIO_BUCKET: default-bucket
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - minio

volumes:
  minio_data:
