spring.application.name=cloudstorage
# Порт приложения
server.port=7474

# Настройка H2 базы данных
spring.datasource.url=jdbc:h2:mem:cloudstorage
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Путь для хранения файлов (будет привязан к серверу через Docker)
file.upload-dir=/app/uploads

# JWT настройки
jwt.secret=${JWT_SECRET}
jwt.expirationMs=86400000

# MyBatis настройка
mybatis.type-aliases-package=com.example.cloudstorage.model
mybatis.mapper-locations=classpath:mapper/*.xml